import type { TexMathFontFamily } from "./font-profile.js";
import type { TexMathAtomClass } from "./ir.js";

export type TexMathSymbolLatexPackage = "amsmath" | "amssymb";

export interface TexMathSymbolDeclaration {
  readonly atomClass: TexMathAtomClass;
  readonly family: TexMathFontFamily;
  readonly code: number;
  readonly requiredLatexPackage: TexMathSymbolLatexPackage | null;
  readonly requiresAmsMathFontProfile: boolean;
}

// TeX Live 2025 amssymb.sty / amsfonts.sty DeclareMathSymbol declarations.
const amsSymbolDeclarations = {
  backepsilon: ams("rel", "amsSymbolsB", 0x7f),
  backprime: ams("ord", "amsSymbolsA", 0x38),
  backsim: ams("rel", "amsSymbolsA", 0x76),
  backsimeq: ams("rel", "amsSymbolsA", 0x77),
  barwedge: ams("bin", "amsSymbolsA", 0x5a),
  because: ams("rel", "amsSymbolsA", 0x2a),
  beth: ams("ord", "amsSymbolsB", 0x69),
  between: ams("rel", "amsSymbolsA", 0x47),
  bigstar: ams("ord", "amsSymbolsA", 0x46),
  blacklozenge: ams("ord", "amsSymbolsA", 0x07),
  blacksquare: ams("ord", "amsSymbolsA", 0x04),
  blacktriangle: ams("ord", "amsSymbolsA", 0x4e),
  blacktriangledown: ams("ord", "amsSymbolsA", 0x48),
  blacktriangleleft: ams("rel", "amsSymbolsA", 0x4a),
  blacktriangleright: ams("rel", "amsSymbolsA", 0x49),
  boxdot: ams("bin", "amsSymbolsA", 0x00),
  boxminus: ams("bin", "amsSymbolsA", 0x0c),
  boxplus: ams("bin", "amsSymbolsA", 0x01),
  boxtimes: ams("bin", "amsSymbolsA", 0x02),
  Bumpeq: ams("rel", "amsSymbolsA", 0x6d),
  bumpeq: ams("rel", "amsSymbolsA", 0x6c),
  Cap: ams("bin", "amsSymbolsA", 0x65),
  centerdot: ams("bin", "amsSymbolsA", 0x05),
  checkmark: ams("ord", "amsSymbolsA", 0x58),
  circeq: ams("rel", "amsSymbolsA", 0x24),
  circlearrowleft: ams("rel", "amsSymbolsA", 0x09),
  circlearrowright: ams("rel", "amsSymbolsA", 0x08),
  circledast: ams("bin", "amsSymbolsA", 0x7e),
  circledcirc: ams("bin", "amsSymbolsA", 0x7d),
  circleddash: ams("bin", "amsSymbolsA", 0x7f),
  circledR: ams("ord", "amsSymbolsA", 0x72),
  circledS: ams("ord", "amsSymbolsA", 0x73),
  complement: ams("ord", "amsSymbolsA", 0x7b),
  Cup: ams("bin", "amsSymbolsA", 0x64),
  curlyeqprec: ams("rel", "amsSymbolsA", 0x32),
  curlyeqsucc: ams("rel", "amsSymbolsA", 0x33),
  curlyvee: ams("bin", "amsSymbolsA", 0x67),
  curlywedge: ams("bin", "amsSymbolsA", 0x66),
  curvearrowleft: ams("rel", "amsSymbolsB", 0x78),
  curvearrowright: ams("rel", "amsSymbolsB", 0x79),
  daleth: ams("ord", "amsSymbolsB", 0x6b),
  diagdown: ams("ord", "amsSymbolsB", 0x1f),
  diagup: ams("ord", "amsSymbolsB", 0x1e),
  Diamond: ams("ord", "amsSymbolsA", 0x06),
  digamma: ams("ord", "amsSymbolsB", 0x7a),
  divideontimes: ams("bin", "amsSymbolsB", 0x3e),
  dotplus: ams("bin", "amsSymbolsA", 0x75),
  doublebarwedge: ams("bin", "amsSymbolsA", 0x5b),
  doublecap: ams("bin", "amsSymbolsA", 0x65),
  doublecup: ams("bin", "amsSymbolsA", 0x64),
  downdownarrows: ams("rel", "amsSymbolsA", 0x15),
  downharpoonleft: ams("rel", "amsSymbolsA", 0x19),
  downharpoonright: ams("rel", "amsSymbolsA", 0x17),
  Doteq: ams("rel", "amsSymbolsA", 0x2b),
  doteqdot: ams("rel", "amsSymbolsA", 0x2b),
  eqcirc: ams("rel", "amsSymbolsA", 0x50),
  eqsim: ams("rel", "amsSymbolsB", 0x68),
  eqslantgtr: ams("rel", "amsSymbolsA", 0x31),
  eqslantless: ams("rel", "amsSymbolsA", 0x30),
  eth: ams("ord", "amsSymbolsB", 0x67),
  fallingdotseq: ams("rel", "amsSymbolsA", 0x3b),
  Finv: ams("ord", "amsSymbolsB", 0x60),
  Game: ams("ord", "amsSymbolsB", 0x61),
  geqq: ams("rel", "amsSymbolsA", 0x3d),
  geqslant: ams("rel", "amsSymbolsA", 0x3e),
  ggg: ams("rel", "amsSymbolsA", 0x6f),
  gggtr: ams("rel", "amsSymbolsA", 0x6f),
  gimel: ams("ord", "amsSymbolsB", 0x6a),
  gnapprox: ams("rel", "amsSymbolsB", 0x1b),
  gneq: ams("rel", "amsSymbolsB", 0x0d),
  gneqq: ams("rel", "amsSymbolsB", 0x09),
  gnsim: ams("rel", "amsSymbolsB", 0x13),
  gtrapprox: ams("rel", "amsSymbolsA", 0x27),
  gtrdot: ams("bin", "amsSymbolsB", 0x6d),
  gtreqless: ams("rel", "amsSymbolsA", 0x52),
  gtreqqless: ams("rel", "amsSymbolsA", 0x54),
  gtrless: ams("rel", "amsSymbolsA", 0x3f),
  gtrsim: ams("rel", "amsSymbolsA", 0x26),
  gvertneqq: ams("rel", "amsSymbolsB", 0x01),
  hslash: ams("ord", "amsSymbolsB", 0x7d),
  intercal: ams("bin", "amsSymbolsA", 0x7c),
  leadsto: ams("rel", "amsSymbolsA", 0x20),
  leftarrowtail: ams("rel", "amsSymbolsA", 0x1b),
  leftleftarrows: ams("rel", "amsSymbolsA", 0x12),
  leftrightarrows: ams("rel", "amsSymbolsA", 0x1c),
  leftrightharpoons: ams("rel", "amsSymbolsA", 0x0b),
  leftrightsquigarrow: ams("rel", "amsSymbolsA", 0x21),
  leftthreetimes: ams("bin", "amsSymbolsA", 0x68),
  leqq: ams("rel", "amsSymbolsA", 0x35),
  leqslant: ams("rel", "amsSymbolsA", 0x36),
  lesseqgtr: ams("rel", "amsSymbolsA", 0x51),
  lesseqqgtr: ams("rel", "amsSymbolsA", 0x53),
  lessapprox: ams("rel", "amsSymbolsA", 0x2f),
  lessdot: ams("bin", "amsSymbolsB", 0x6c),
  lessgtr: ams("rel", "amsSymbolsA", 0x37),
  lesssim: ams("rel", "amsSymbolsA", 0x2e),
  lhd: ams("bin", "amsSymbolsA", 0x43),
  lll: ams("rel", "amsSymbolsA", 0x6e),
  llless: ams("rel", "amsSymbolsA", 0x6e),
  llcorner: ams("open", "amsSymbolsA", 0x78),
  Lleftarrow: ams("rel", "amsSymbolsA", 0x57),
  lneq: ams("rel", "amsSymbolsB", 0x0c),
  lneqq: ams("rel", "amsSymbolsB", 0x08),
  lnapprox: ams("rel", "amsSymbolsB", 0x1a),
  lnsim: ams("rel", "amsSymbolsB", 0x12),
  looparrowleft: ams("rel", "amsSymbolsA", 0x22),
  looparrowright: ams("rel", "amsSymbolsA", 0x23),
  lozenge: ams("ord", "amsSymbolsA", 0x06),
  lrcorner: ams("close", "amsSymbolsA", 0x79),
  ltimes: ams("bin", "amsSymbolsB", 0x6e),
  lvertneqq: ams("rel", "amsSymbolsB", 0x00),
  maltese: ams("ord", "amsSymbolsA", 0x7a),
  measuredangle: ams("ord", "amsSymbolsA", 0x5d),
  mho: ams("ord", "amsSymbolsB", 0x66),
  multimap: ams("rel", "amsSymbolsA", 0x28),
  ngeq: ams("rel", "amsSymbolsB", 0x03),
  ngeqq: ams("rel", "amsSymbolsB", 0x15),
  ngeqslant: ams("rel", "amsSymbolsB", 0x0b),
  ngtr: ams("rel", "amsSymbolsB", 0x05),
  nLeftarrow: ams("rel", "amsSymbolsB", 0x3a),
  nLeftrightarrow: ams("rel", "amsSymbolsB", 0x3c),
  nleftarrow: ams("rel", "amsSymbolsB", 0x38),
  nleftrightarrow: ams("rel", "amsSymbolsB", 0x3d),
  nleq: ams("rel", "amsSymbolsB", 0x02),
  nleqq: ams("rel", "amsSymbolsB", 0x14),
  nleqslant: ams("rel", "amsSymbolsB", 0x0a),
  nless: ams("rel", "amsSymbolsB", 0x04),
  ncong: ams("rel", "amsSymbolsB", 0x1d),
  nmid: ams("rel", "amsSymbolsB", 0x2d),
  nparallel: ams("rel", "amsSymbolsB", 0x2c),
  nprec: ams("rel", "amsSymbolsB", 0x06),
  npreceq: ams("rel", "amsSymbolsB", 0x0e),
  nRightarrow: ams("rel", "amsSymbolsB", 0x3b),
  nrightarrow: ams("rel", "amsSymbolsB", 0x39),
  nshortmid: ams("rel", "amsSymbolsB", 0x2e),
  nshortparallel: ams("rel", "amsSymbolsB", 0x2f),
  nsim: ams("rel", "amsSymbolsB", 0x1c),
  nsubseteq: ams("rel", "amsSymbolsB", 0x2a),
  nsubseteqq: ams("rel", "amsSymbolsB", 0x22),
  nsucc: ams("rel", "amsSymbolsB", 0x07),
  nsucceq: ams("rel", "amsSymbolsB", 0x0f),
  nsupseteq: ams("rel", "amsSymbolsB", 0x2b),
  nsupseteqq: ams("rel", "amsSymbolsB", 0x23),
  ntriangleleft: ams("rel", "amsSymbolsB", 0x36),
  ntrianglelefteq: ams("rel", "amsSymbolsB", 0x35),
  ntriangleright: ams("rel", "amsSymbolsB", 0x37),
  ntrianglerighteq: ams("rel", "amsSymbolsB", 0x34),
  nvDash: ams("rel", "amsSymbolsB", 0x32),
  nVdash: ams("rel", "amsSymbolsB", 0x31),
  nVDash: ams("rel", "amsSymbolsB", 0x33),
  nvdash: ams("rel", "amsSymbolsB", 0x30),
  pitchfork: ams("rel", "amsSymbolsA", 0x74),
  precapprox: ams("rel", "amsSymbolsB", 0x77),
  preccurlyeq: ams("rel", "amsSymbolsA", 0x34),
  precnapprox: ams("rel", "amsSymbolsB", 0x18),
  precneqq: ams("rel", "amsSymbolsB", 0x16),
  precnsim: ams("rel", "amsSymbolsB", 0x10),
  precsim: ams("rel", "amsSymbolsA", 0x2d),
  restriction: ams("rel", "amsSymbolsA", 0x16),
  rightarrowtail: ams("rel", "amsSymbolsA", 0x1a),
  rightleftarrows: ams("rel", "amsSymbolsA", 0x1d),
  rightleftharpoons: ams("rel", "amsSymbolsA", 0x0a),
  rightrightarrows: ams("rel", "amsSymbolsA", 0x13),
  rightsquigarrow: ams("rel", "amsSymbolsA", 0x20),
  rhd: ams("bin", "amsSymbolsA", 0x42),
  risingdotseq: ams("rel", "amsSymbolsA", 0x3a),
  Rrightarrow: ams("rel", "amsSymbolsA", 0x56),
  Rsh: ams("rel", "amsSymbolsA", 0x1f),
  rtimes: ams("bin", "amsSymbolsB", 0x6f),
  shortmid: ams("rel", "amsSymbolsB", 0x70),
  shortparallel: ams("rel", "amsSymbolsB", 0x71),
  smallfrown: ams("rel", "amsSymbolsA", 0x61),
  smallsetminus: ams("bin", "amsSymbolsB", 0x72),
  smallsmile: ams("rel", "amsSymbolsA", 0x60),
  sphericalangle: ams("ord", "amsSymbolsA", 0x5e),
  sqsubset: ams("rel", "amsSymbolsA", 0x40),
  sqsupset: ams("rel", "amsSymbolsA", 0x41),
  square: ams("ord", "amsSymbolsA", 0x03),
  Subset: ams("rel", "amsSymbolsA", 0x62),
  subsetneq: ams("rel", "amsSymbolsB", 0x28),
  subsetneqq: ams("rel", "amsSymbolsB", 0x24),
  subseteqq: ams("rel", "amsSymbolsA", 0x6a),
  succapprox: ams("rel", "amsSymbolsB", 0x76),
  succcurlyeq: ams("rel", "amsSymbolsA", 0x3c),
  succnapprox: ams("rel", "amsSymbolsB", 0x19),
  succneqq: ams("rel", "amsSymbolsB", 0x17),
  succnsim: ams("rel", "amsSymbolsB", 0x11),
  succsim: ams("rel", "amsSymbolsA", 0x25),
  Supset: ams("rel", "amsSymbolsA", 0x63),
  supsetneq: ams("rel", "amsSymbolsB", 0x29),
  supsetneqq: ams("rel", "amsSymbolsB", 0x25),
  supseteqq: ams("rel", "amsSymbolsA", 0x6b),
  therefore: ams("rel", "amsSymbolsA", 0x29),
  thickapprox: ams("rel", "amsSymbolsB", 0x74),
  thicksim: ams("rel", "amsSymbolsB", 0x73),
  trianglelefteq: ams("rel", "amsSymbolsA", 0x45),
  triangleq: ams("rel", "amsSymbolsA", 0x2c),
  triangledown: ams("ord", "amsSymbolsA", 0x4f),
  trianglerighteq: ams("rel", "amsSymbolsA", 0x44),
  twoheadleftarrow: ams("rel", "amsSymbolsA", 0x11),
  twoheadrightarrow: ams("rel", "amsSymbolsA", 0x10),
  ulcorner: ams("open", "amsSymbolsA", 0x70),
  unlhd: ams("bin", "amsSymbolsA", 0x45),
  unrhd: ams("bin", "amsSymbolsA", 0x44),
  upharpoonleft: ams("rel", "amsSymbolsA", 0x18),
  upharpoonright: ams("rel", "amsSymbolsA", 0x16),
  upuparrows: ams("rel", "amsSymbolsA", 0x14),
  urcorner: ams("close", "amsSymbolsA", 0x71),
  vartriangle: ams("rel", "amsSymbolsA", 0x4d),
  vartriangleleft: ams("rel", "amsSymbolsA", 0x43),
  vartriangleright: ams("rel", "amsSymbolsA", 0x42),
  varkappa: ams("ord", "amsSymbolsB", 0x7b),
  varnothing: ams("ord", "amsSymbolsB", 0x3f),
  varpropto: ams("rel", "amsSymbolsA", 0x5f),
  varsubsetneq: ams("rel", "amsSymbolsB", 0x20),
  varsubsetneqq: ams("rel", "amsSymbolsB", 0x26),
  varsupsetneq: ams("rel", "amsSymbolsB", 0x21),
  varsupsetneqq: ams("rel", "amsSymbolsB", 0x27),
  vDash: ams("rel", "amsSymbolsA", 0x0f),
  Vdash: ams("rel", "amsSymbolsA", 0x0d),
  veebar: ams("bin", "amsSymbolsA", 0x59),
  Vvdash: ams("rel", "amsSymbolsA", 0x0e),
  yen: ams("ord", "amsSymbolsA", 0x55),
  Box: ams("ord", "amsSymbolsA", 0x03),
  Lsh: ams("rel", "amsSymbolsA", 0x1e),
  nexists: ams("ord", "amsSymbolsB", 0x40),
  rightthreetimes: ams("bin", "amsSymbolsA", 0x69),
  varGamma: amsmath("ord", "letters", 0x00),
  varDelta: amsmath("ord", "letters", 0x01),
  varTheta: amsmath("ord", "letters", 0x02),
  varLambda: amsmath("ord", "letters", 0x03),
  varXi: amsmath("ord", "letters", 0x04),
  varPi: amsmath("ord", "letters", 0x05),
  varSigma: amsmath("ord", "letters", 0x06),
  varUpsilon: amsmath("ord", "letters", 0x07),
  varPhi: amsmath("ord", "letters", 0x08),
  varPsi: amsmath("ord", "letters", 0x09),
  varOmega: amsmath("ord", "letters", 0x0a),
} as const satisfies Record<string, TexMathSymbolDeclaration>;

export function texMathSymbolDeclaration(command: string): TexMathSymbolDeclaration | null {
  const name = command.startsWith("\\") ? command.slice(1) : command;
  return (amsSymbolDeclarations as Record<string, TexMathSymbolDeclaration>)[name] ?? null;
}

export function texMathSymbolCommandNames(options: {
  readonly requiredLatexPackage?: TexMathSymbolLatexPackage;
} = {}): readonly string[] {
  return Object.entries(amsSymbolDeclarations)
    .filter(([, declaration]) =>
      options.requiredLatexPackage === undefined ||
      declaration.requiredLatexPackage === options.requiredLatexPackage
    )
    .map(([name]) => `\\${name}`);
}

function ams(
  atomClass: TexMathAtomClass,
  family: TexMathFontFamily,
  code: number
): TexMathSymbolDeclaration {
  return {
    atomClass,
    family,
    code,
    requiredLatexPackage: "amssymb",
    requiresAmsMathFontProfile: true,
  };
}

function amsmath(
  atomClass: TexMathAtomClass,
  family: TexMathFontFamily,
  code: number
): TexMathSymbolDeclaration {
  return {
    atomClass,
    family,
    code,
    requiredLatexPackage: "amsmath",
    requiresAmsMathFontProfile: false,
  };
}
