// Compatibility barrel for the editor geometry API. The filename is retained
// temporarily because it is part of the published subpath surface.
export {
  getKnuthPlassCaretFromPoint,
  getKnuthPlassLineRangeFromPoint,
  getKnuthPlassPlaceholderGeometry,
  getKnuthPlassPointFromOffset,
  getKnuthPlassSelectionRects,
  getKnuthPlassVListBoxFromPoint,
  getKnuthPlassVListBoxGeometry,
  getKnuthPlassVListGeometrySnapshot,
  getKnuthPlassVListItemFromPoint,
  getKnuthPlassVListLabelFromPoint,
  getKnuthPlassVListItemGeometry,
  getKnuthPlassVListLabelGeometry,
  getKnuthPlassVListParagraphGeometry,
  getKnuthPlassVListSourceHit,
  getKnuthPlassVListSourceHitFromSnapshot,
  getKnuthPlassVListTreeHitFromSnapshot,
  clearKnuthPlassCaretMappingCache,
  type CaretFromPointParams,
  type PointFromOffsetParams,
  type SelectionRectsParams,
  type CaretHitResult,
  type LineRangeFromPointResult,
  type CaretPointResult,
  type PlaceholderGeometry,
  type PlaceholderGeometryParams,
  type SelectionRectsResult,
  type VListBoxHitParams,
  type VListBoxGeometry,
  type VListBoxGeometryParams,
  type VListGeometrySnapshot,
  type VListGeometrySnapshotParams,
  type VListGeometrySnapshotSource,
  type VListGeometryTreeNode,
  type VListItemHitParams,
  type VListItemGeometry,
  type VListItemGeometryParams,
  type VListLabelHitParams,
  type VListLabelHitResult,
  type VListLabelGeometry,
  type VListLabelGeometryParams,
  type VListParagraphGeometry,
  type VListParagraphGeometryParams,
  type VListSourceHit,
  type VListSourceHitFromSnapshotParams,
  type VListSourceHitParams,
  type VListTreeHitParams,
  type VListTreeHitResult,
} from "./editor/hitmap.js";
