/** @vitest-environment jsdom */

import { act, createElement } from "react";
import { createRoot, type Root } from "react-dom/client";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { renderTikzToSvg } from "../../packages/core/src/render/index.js";
import { OPEN_EXAMPLE_CATALOG } from "../../packages/app/src/ui/examples/open-example-catalog.js";
import {
  useCanvasSelectionDerivedState,
  type UseCanvasSelectionDerivedStateArgs
} from "../../packages/app/src/ui/canvas-panel/useCanvasSelectionDerivedState.js";

let root: Root | undefined;
let derived: ReturnType<typeof useCanvasSelectionDerivedState>;

function Harness({ args }: { args: UseCanvasSelectionDerivedStateArgs }) {
  derived = useCanvasSelectionDerivedState(args);
  return null;
}

beforeEach(() => {
  vi.stubGlobal("IS_REACT_ACT_ENVIRONMENT", true);
});

afterEach(async () => {
  if (root) await act(async () => root!.unmount());
  root = undefined;
  vi.unstubAllGlobals();
});

async function selectSource(source: string, sourceId: string) {
  const rendered = renderTikzToSvg(source);
  root = createRoot(document.createElement("div"));
  await act(async () => root!.render(createElement(Harness, { args: {
    snapshot: {
      source,
      scene: rendered.semantic.scene,
      editHandles: rendered.semantic.editHandles,
      parseResult: rendered.parse,
      semanticResult: rendered.semantic
    },
    selectedElementIds: new Set([sourceId]),
    collapsedDensePathSourceIds: new Set<string>(),
    svgResult: rendered.svg,
    canvasTransform: { translateX: 0, translateY: 0, scale: 1 },
    marqueeDraft: null,
    toolMode: "select",
    viewportSize: { width: 1024, height: 768 },
    ROTATE_HANDLE_OFFSET_PX: 24
  } })));
}

it("keeps the plot y-tick group outlined without offering resize or rotation", async () => {
  const source = OPEN_EXAMPLE_CATALOG.find(example => example.id === "axes")!.source;
  await selectSource(source, "foreach:3");

  expect(derived.selectionBoxes.some(box => box.sourceId === "foreach:3")).toBe(true);
  expect(derived.resizeFrameSourceIds.has("foreach:3")).toBe(false);
  expect(derived.handleDisplays.some(handle =>
    handle.kind === "resize-element" || handle.kind === "rotate-element"
  )).toBe(false);
});

it("does not offer resize handles for a circle generated by a foreach loop", async () => {
  await selectSource(String.raw`\begin{tikzpicture}
  \foreach \y in {1} { \draw (0,\y) circle (3pt); }
\end{tikzpicture}`, "foreach:0");

  expect(derived.handleDisplays.some(handle => handle.kind === "resize-element")).toBe(false);
});

it.each([
  String.raw`\node[text width=2cm] at (0,0) {Hello wrapped world};`,
  String.raw`\draw (0,0) -- node[above] {label} (3,0);`
])("keeps resize handles for an editable node: %s", async statement => {
  const source = String.raw`\begin{tikzpicture}${statement}\end{tikzpicture}`;
  const rendered = renderTikzToSvg(source);
  const text = rendered.semantic.scene.elements.find(element => element.kind === "Text")!;
  await selectSource(source, text.sourceRef.sourceId);

  expect(derived.handleDisplays.some(handle => handle.kind === "resize-element")).toBe(true);
});
