export {
  ComputerModernTexMetricProvider,
  DEFAULT_COMPUTER_MODERN_TEXT_FONTS,
  computerModernTexMetricProvider,
  type DefaultComputerModernTextFont,
  type ResolveComputerModernFontOptions,
} from "./fonts/computer-modern.js";
export {
  getSimpleTexFallbackReason,
  layoutSimpleTexParagraph,
  type TexParagraphAlignment,
  type TexParagraphLayoutOptions,
  type TexParagraphLayoutResult,
} from "./paragraph.js";
export {
  parseSimpleTexParagraphIr,
  type SimpleTexAlignmentNode,
  type SimpleTexControlNode,
  type SimpleTexEnvironmentBoundaryNode,
  type SimpleTexFontCommandName,
  type SimpleTexFontCommandNode,
  type SimpleTexFontDeclarationName,
  type SimpleTexFontDeclarationNode,
  type SimpleTexFontState,
  type SimpleTexGroupNode,
  type SimpleTexInlineNode,
  type SimpleTexLineBreakNode,
  type SimpleTexNoIndentNode,
  type SimpleTexNode,
  type SimpleTexParagraphBreakNode,
  type SimpleTexParagraphBlock,
  type SimpleTexParagraphIr,
  type SimpleTexParagraphSegment,
  type SimpleTexSpaceNode,
  type SimpleTexTextNode,
  type SimpleTexToken,
  type SimpleTexUnsupportedCommandNode,
  type TexAlignmentProfile,
  type TexFontFamily,
  type TexFontSeries,
  type TexFontShape,
  type TexSpaceGlueProfile,
} from "./ir.js";
export {
  createSimpleTexLayoutDocumentIr,
  type SimpleTexLayoutDocumentIr,
  type TexLayoutForcedBreakItem,
  type TexLayoutInlineItem,
  type TexLayoutIrOptions,
  type TexLayoutParagraphIr,
  type TexLayoutSpaceItem,
  type TexLayoutTextItem,
} from "./layout-ir.js";
export type {
  GeneratedTexCharMetric,
  GeneratedTexFont,
  GeneratedTexFontTable,
  GeneratedTexLigKern,
  ResolvedTexFont,
  ShapeTexTextOptions,
  ShapedTexTextRun,
  TexCaretStop,
  TexGlyphBox,
  TexKern,
  TexShapedItem,
} from "./fonts/types.js";
