export {
  ComputerModernTexMetricProvider,
  DEFAULT_COMPUTER_MODERN_TEXT_FONTS,
  computerModernTexMetricProvider,
  type DefaultComputerModernTextFont,
  type ResolveComputerModernFontOptions,
} from "./fonts/computer-modern.js";
export {
  analyzeSimpleTexParagraph,
  getSimpleTexFallbackReason,
  layoutSimpleTexParagraph,
  type TexParagraphAlignment,
  type TexParagraphLayoutOptions,
  type TexParagraphLayoutResult,
} from "./paragraph.js";
export {
  parseSimpleTexParagraphIr,
  type SimpleTexAlignmentNode,
  type SimpleTexBlockItem,
  type SimpleTexControlNode,
  type SimpleTexEnvironmentBoundaryNode,
  type SimpleTexFontCommandName,
  type SimpleTexFontCommandNode,
  type SimpleTexFontDeclarationName,
  type SimpleTexFontDeclarationNode,
  type SimpleTexFontState,
  type SimpleTexGroupNode,
  type SimpleTexInlineNode,
  type SimpleTexLineBreakNode,
  type SimpleTexNoIndentNode,
  type SimpleTexNode,
  type SimpleTexParagraphBreakNode,
  type SimpleTexParagraphBlock,
  type SimpleTexParagraphIr,
  type SimpleTexParagraphSegment,
  type SimpleTexSegmentInput,
  type SimpleTexPlaceholderBlockItem,
  type SimpleTexSpaceNode,
  type SimpleTexTextNode,
  type SimpleTexToken,
  type SimpleTexUnsupportedCommandNode,
  type SimpleTexVerticalGlueBlockItem,
  type SimpleTexVerticalGlueCommandName,
  type SimpleTexVerticalGlueNode,
  type SimpleTexVerticalRuleBlockItem,
  type SimpleTexVerticalRuleNode,
  type TexAlignmentProfile,
  type TexFontFamily,
  type TexFontSeries,
  type TexFontShape,
  type TexSpaceGlueProfile,
} from "./ir.js";
export {
  createSimpleTexLayoutDocumentIr,
  type SimpleTexLayoutDocumentIr,
  type TexLayoutForcedBreakItem,
  type TexLayoutInlineItem,
  type TexLayoutIrOptions,
  type TexLayoutParagraphIr,
  type TexLayoutSpaceItem,
  type TexLayoutTextItem,
} from "./layout-ir.js";
export {
  addParagraphVerticalGlueToVList,
  computeTexVListNaturalTotalHeight,
  findPositionedTexVListItemByPath,
  flattenPositionedTexVListItems,
  getTexVListLayoutFromOutputJax,
  getTexVListLayoutsFromOutputJax,
  groupSimpleTexVListScopes,
  layoutTexVListItems,
  layoutTexVListFromMeasuredParagraphs,
  layoutTexVListFromParagraphReport,
  lowerSimpleTexBlockItemsToVList,
  lowerSimpleTexBlocksToVList,
  materializeParagraphVerticalGlueInVList,
  measureTexVListParagraphBoxesFromReport,
  measuredBoxMetricsForVListItem,
  metricsForRootBox,
  normalizeSimpleTexVList,
  offsetPositionedTexVListItems,
  planSimpleTexParagraphVerticalSkips,
  prepareSimpleTexVList,
  registerTexVListLayoutsOnOutputJax,
  texVListBaselineY,
  texVListBoxLayoutReport,
  texVListGlueSetForTargetHeight,
  texVListParagraphEntries,
  texVListParagraphItems,
  texVListRootVerticalOffset,
  type MeasuredTexVListItem,
  type PreparedSimpleTexVList,
  type RegisteredTexVListLayout,
  type SimpleTexParagraphVerticalSkip,
  type TexVListGlueSet,
  type TexVListItemMeasurer,
  type TexVListMeasuredParagraphLayoutOptions,
  type TexVListParagraphReportLayoutOptions,
  type PositionedTexVListItem,
  type TexBoxMetrics,
  type TexDimenExpr,
  type TexGlueItem,
  type TexGlueOrder,
  type TexHBoxRole,
  type TexHBoxItem,
  type TexHitMap,
  type TexHorizontalLayout,
  type TexLayoutReport,
  type TexLineBox,
  type TexParagraphItem,
  type TexParagraphInput,
  type TexPenaltyItem,
  type TexPlaceholderItem,
  type TexRenderItem,
  type TexRuleItem,
  type TexSourceSpan,
  type TexVBoxBaseline,
  type TexVListBoxLayoutReport,
  type TexVListBoxReportItem,
  type TexVBoxItem,
  type TexVBoxLayout,
  type TexVBoxListItemDescriptionLayout,
  type TexVBoxListItemLabelBox,
  type TexVBoxListItemLabelContent,
  type TexVBoxListItemLabelKind,
  type TexVBoxListItemLabelPlacement,
  type TexVBoxListItemLayout,
  type TexVBoxListLayout,
  type TexVBoxRole,
  type TexVListParagraphEntry,
  type TexVListDocument,
  type TexVListItem,
  type TexVListLayout,
  type TexVListLayoutOptions,
  type TexVListLinePlacement,
  type TexVListParagraphBoxMeasurement,
  type TexVListParagraphHorizontalLayout,
  type TexVListParagraphLineAssignment,
  type TexVListParagraphLineOffset,
  type TexVListParagraphPlacement,
} from "./vlist/index.js";
export type {
  GeneratedTexCharMetric,
  GeneratedTexFont,
  GeneratedTexFontTable,
  GeneratedTexLigKern,
  ResolveTexFontOptions,
  ResolvedTexFont,
  ShapeTexTextOptions,
  ShapedTexTextRun,
  TexCaretStop,
  TexGlyphBox,
  TexKern,
  TexMetricProvider,
  TexShapedItem,
} from "./fonts/types.js";
